// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbbYB04_pwrU9YeH1dFlscV60Fmyr4-9w',
    appId: '1:452304619317:web:53e04e62c297fd34f3ee7c',
    messagingSenderId: '452304619317',
    projectId: 'medirec-49438',
    authDomain: 'medirec-49438.firebaseapp.com',
    storageBucket: 'medirec-49438.appspot.com',
    measurementId: 'G-9PX4CQ7XCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuiiOCOMPiGxQz-BeTu-7lNfe-7F4sapU',
    appId: '1:452304619317:android:30c08afa80a455f4f3ee7c',
    messagingSenderId: '452304619317',
    projectId: 'medirec-49438',
    storageBucket: 'medirec-49438.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKWUNt7pmNPRZHAv06WQ0Hmgsn92ck5vY',
    appId: '1:452304619317:ios:9852d47e74085283f3ee7c',
    messagingSenderId: '452304619317',
    projectId: 'medirec-49438',
    storageBucket: 'medirec-49438.appspot.com',
    iosClientId: '452304619317-dml265l4l7vnd576arqipqj08tpb63pd.apps.googleusercontent.com',
    iosBundleId: 'com.pavan72362.medirec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKWUNt7pmNPRZHAv06WQ0Hmgsn92ck5vY',
    appId: '1:452304619317:ios:9852d47e74085283f3ee7c',
    messagingSenderId: '452304619317',
    projectId: 'medirec-49438',
    storageBucket: 'medirec-49438.appspot.com',
    iosClientId: '452304619317-dml265l4l7vnd576arqipqj08tpb63pd.apps.googleusercontent.com',
    iosBundleId: 'com.pavan72362.medirec',
  );
}
